name: Deploy Laravel Project

on:
  push:
    branches: [ main ] # Se ejecuta cuando haces push a main

jobs:
  web-deploy:
    name: Deploying to Shared Hosting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Dependencies (Composer)
      run: composer install --no-dev --optimize-autoloader

    - name: Create .env file
      run: echo "${{ secrets.DOT_ENV }}" > .env

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # O la versión que uses localmente

    - name: Install NPM dependencies & Build
      run: |
        npm install
        npm run build

    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Aquí defines la carpeta de destino en el servidor
        server-dir: ./laravel/
        # Excluye carpetas innecesarias para ahorrar tiempo y espacio
        # **/vendor/** Si deseas que el proyecto cargue vendor automáticamente, descomentar linea correspondiente. Tiempo de subida de vendor 1h 13min
        exclude: |
          **/.git*
          **/node_modules/**
          **/tests/**
          storage/*.sqlite
    - name: Finalize Deployment (Run Migrations & Cache)
      run: curl -s "${{ secrets.DOMINIO }}/deploy-finish"
    
    - name: Create Storage Link
      run: curl -s "${{ secrets.DOMINIO }}/link-storage"